################################# Insurer #############################################
### Get all
GET http://localhost:8080/project/api/insurers/all
Accept: application/json

### Get one
GET http://localhost:8080/project/api/insurers/3
Accept: application/json

### Post one
POST http://localhost:8080/project/api/insurers
Content-Type: application/json

{
  "id": 99,
  "name": "Test Insurer"
}

### Put one
PUT http://localhost:8080/project/api/insurers/3
Content-Type: application/json

{
  "id": 3,
  "name": "Test Insurer"
}

### Delete one
DELETE http://localhost:8080/project/api/insurers/3
Accept: application/json

################################# Insurer Experts #############################################
###Get all
GET http://localhost:8080/project/api/insurer_experts/all
Accept: application/json

###Get one
GET http://localhost:8080/project/api/insurer_experts/5
Accept: application/json

###Post one
POST http://localhost:8080/project/api/insurer_experts
Content-Type: application/json

{
  "id": 27,
  "name": "Test Insurer Expert",
  "email": "asdsd@sdd",
  "password": "asd",
  "insurer_id": 10
}

###Put one
PUT http://localhost:8080/project/api/insurer_experts/5
Content-Type: application/json

{
  "id": 5,
  "name": "Test Insurer Expert",
  "email": "asdsd@sdd",
  "password": "asd",
  "insurer_id": 10
}

###Delete one
DELETE http://localhost:8080/project/api/insurer_experts/5
Accept: application/json

################################# Historicals #############################################
###Get all
GET http://localhost:8080/project/api/historical/all
Accept: application/json

###Get one
GET http://localhost:8080/project/api/historical/1
Accept: application/json

###Update one
PUT http://localhost:8080/project/api/historical/1
Content-Type: application/json

{
  "id": 1,
  "state": "APROVADO_PELA_SEGURADORA",
  "description": "Test description 2.0",
  "date": "3921-07-01T00:00:00Z[UTC]"
}

###DELETE one
DELETE http://localhost:8080/project/api/historical/1
Accept: application/json

################################# PolicyObject #############################################

###Get all
GET http://localhost:8080/project/api/policy_objects/all
Accept: application/json

###Get one
GET http://localhost:8080/project/api/policy_objects/1
Accept: application/json

###Create one
POST http://localhost:8080/project/api/policy_objects/
Content-Type: application/json

{
  "id": 2,
  "name": "Test Policy Object",
  "filePath": "C:\\Users\\filipe\\Desktop\\telefone.jpg"
}

###Update one
PUT http://localhost:8080/project/api/policy_objects/1
Content-Type: application/json

{
  "id": 2,
  "name": "Test Policy Object-Updated",
  "filePath": "C:\\Users\\filipe\\Desktop\\GRRR.jpg"
}

###Delete one
DELETE http://localhost:8080/project/api/policy_objects/2
Accept: application/json

################################# RepairShop #############################################

###Get all
GET http://localhost:8080/project/api/repair_shops/all
Accept: application/json

###Get one
GET http://localhost:8080/project/api/repair_shops/100
Accept: application/json

###Create one
POST http://localhost:8080/project/api/repair_shops/
Content-Type: application/json

{
  "id": 100,
  "name": "Test Repair Shop",
  "email": "teste@mail.pt",
  "phone": "123456789"
}

###Update one
PUT http://localhost:8080/project/api/repair_shops/100
Content-Type: application/json

{
  "id": 100,
  "name": "Test Repair Shop- Updated",
  "email": "teste@mail.pt",
  "phone": "999999999"
}

###Delete one
DELETE http://localhost:8080/project/api/repair_shops/100
Accept: application/json
