package pt.ipleiria.estg.dei.ei.dae.project.enteties.enums;

public enum HistoricalEnum {
    APROVADO_PELA_SEGURADORA,
    NAO_APROVADO_PELA_SEGURADORA,
    APROVADO_PELO_EXPERT,
    NAO_APROVADO_PELO_EXPERT,
    A_AGUARDAR_APROVACAO_PELO_EXPERT,
    A_AGUARDAR_APROVACAO_PELA_SEGURADORA,
}
